routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $data['background'] = false;
    $data['title'] = "Wisata Minang";
    return view('welcome',$data);
});

Auth::routes();


Route::resource('coba','CobaController');
Route::resource('informasi','InformasiController');
Route::resource('kategori','KategoriController');
Route::resource('polling','PollingController');


Route::get('/admin/dashboard', 'HomeController@index')->name('dashboard');
Route::get('/detail/{id}', 'FrontendController@detail')->name('detail');

Route::prefix('admin/kategori')->namespace('AdminController')->group(function() 
{
    Route::get('/create', 'KategoriController@create')->name('createKategori');
    Route::post('/create','KategoriController@store')->name('storeKategori');
    Route::get('/index','KategoriController@index')->name('indexKategori');
});


Route::prefix('admin/informasi')->namespace('AdminController')->group(function()
{
    Route::get('/create','InformasiController@create')->name('createInformasi');
    Route::post('/create','InformasiController@store')->name('storeInformasi');
    Route::get('/index','InformasiController@index')->name('indexInformasi');
    Route::get('/edit','InformasiController@edit')->name('editInformasi');
});


Route::prefix('admin/pesan')->namespace('AdminController')->group(function()
{
    Route::get('/index','PesanController@index')->name('indexPesan');
    Route::get('/validation/{id}', 'PesanController@validation')->name('validation');
    Route::get('/validationNo/{id}', 'PesanController@validationNo')->name('validationNo');
    Route::get('/{id}', 'PesanController@destroy')->name('hapusPesan');

});

Route::prefix('frontend/kontak')->group(function()
{
	Route::get('','FrontendController@showpesan')->name('showPesan');
	Route::post('', 'FrontendController@store')->name('storePesan');
});

Route::get('/frontend/alam', 'FrontendController@indexalam')->name('indexAlam');

Route::get('/frontend/kuliner', 'FrontendController@indexkuliner')->name('indexKuliner');

Route::get('/frontend/edukasi', 'FrontendController@indexedu')->name('indexEdu');

Route::get('/frontend/budaya', 'FrontendController@indexbudaya')->name('indexBudaya');

Route::post('/welcome/{succes}', 'FrontendController@polling')->name('storePolling');




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Informasi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Informasi extends Model
{
    protected $table = "informasi";
}

app/Http/Controllers/AdminController/InformasiController.php
<?php

namespace App\Http\Controllers\AdminController;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Informasi;
use App\Kategori;
use App\Http\Controllers\Auth;

class InformasiController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $informasis = Informasi::paginate(8);
        return view('admin.informasi.index', compact('informasis'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kategoris = Kategori::All();
        return view('admin.informasi.create', compact('kategoris'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $kategoris = Kategori::All();
        $inputinfo = New Informasi;
        $inputinfo->judul = $request->judul;
        $inputinfo->id_kategori = $request->id_kategori;
        $inputinfo->jalan = $request->jalan;
        $inputinfo->kelkec = $request->kelkec;
        $inputinfo->kotakab = $request->kotakab;
        $inputinfo->provinsi = $request->provinsi;
        $inputinfo->konten = $request->konten;
        $inputinfo->peta = $request->peta;
        $gambar1 = $request->foto1;
            $namagambar1 = $gambar1->getClientOriginalName();
            $gambar1->move('images', $namagambar1);
        $inputinfo->foto1 = $namagambar1;
        $gambar2 = $request->foto2;
            $namagambar2 = $gambar2->getClientOriginalName();
            $gambar2->move('images', $namagambar2);
        $inputinfo->foto2 = $namagambar2;
        $gambar3 = $request->foto3;
            $namagambar3 = $gambar3->getClientOriginalName();
            $gambar3->move('images', $namagambar3);
        $inputinfo->foto3 = $namagambar3;
        $inputinfo->save();
        return view('admin.informasi.create', compact('kategoris'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        return $id;        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return $id;
    }
}

app/Http/Controllers/InformasiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Informasi;
use App\Kategori;

class InformasiController extends Controller
{
     
    public function index()
    {
        $informasis = Informasi::paginate(8);
        return view('admin.informasi.index', compact('informasis'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kategoris = Kategori::All();
        return view('admin.informasi.create', compact('kategoris'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $kategoris = Kategori::All();
        $inputinfo = New Informasi;
        $inputinfo->judul = $request->judul;
        $inputinfo->id_kategori = $request->id_kategori;
        $inputinfo->jalan = $request->jalan;
        $inputinfo->kelkec = $request->kelkec;
        $inputinfo->kotakab = $request->kotakab;
        $inputinfo->provinsi = $request->provinsi;
        $inputinfo->konten = $request->konten;
        $inputinfo->peta = $request->peta;

        $gambar1 = $request->foto1;
            $namagambar1 = $gambar1->getClientOriginalName();
            $gambar1->move('images', $namagambar1);
        $inputinfo->foto1 = $namagambar1;

        $gambar2 = $request->foto2;
            $namagambar2 = $gambar2->getClientOriginalName();
            $gambar2->move('images', $namagambar2);
        $inputinfo->foto2 = $namagambar2;
        
        $gambar3 = $request->foto3;
            $namagambar3 = $gambar3->getClientOriginalName();
            $gambar3->move('images', $namagambar3);
        $inputinfo->foto3 = $namagambar3;
        $inputinfo->save();
        return view('admin.informasi.create', compact('kategoris'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['kategoris'] = Kategori::All();
        $data['informasi'] = Informasi::find($id);
        return view('admin.informasi.edit',$data);
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $updateInformasi =  \App\Informasi::findOrFail($id);
        $updateInformasi->judul = $request->get('judul');
        $updateInformasi->id_kategori = $request->get('id_kategori');
        $updateInformasi->provinsi = $request->get('provinsi');
        $updateInformasi->kotakab = $request->get('kotakab');
        $updateInformasi->kelkec = $request->get('kelkec');
        $updateInformasi->konten = $request->get('konten');
        $updateInformasi->peta = $request->get('peta');
        $updateInformasi->jalan = $request->get('jalan');
        if($request->populer) {
            $inputstatus = $request->populer;
            $updateInformasi->status = $inputstatus;
        }

        $gambar1 = $request->foto1;
            $namagambar1 = $gambar1->getClientOriginalName();
            $gambar1->move('images', $namagambar1);
        $updateInformasi->foto1 = $namagambar1;


        $gambar2 = $request->foto2;
            $namagambar2 = $gambar2->getClientOriginalName();
            $gambar2->move('images', $namagambar2);
        $updateInformasi->foto2 = $namagambar2;

        $gambar3 = $request->foto3;
            $namagambar3 = $gambar3->getClientOriginalName();
            $gambar3->move('images', $namagambar3);
        $updateInformasi->foto3 = $namagambar3;
        $updateInformasi->save();

        return redirect('informasi');
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $informasi = Informasi::findOrFail($id);
        $informasi->delete();
        return back();
    }
}

resources/views/admin/informasi/create.blade.php
@extends('admin.master')
@section('content')
<div class="card">
<form action="{{route('storeInformasi')}}" method="post" enctype="multipart/form-data" class="form-horizontal">
{{csrf_field()}}
        <div class="card-body">
            <h4 class="card-title">Input Informasi Wisata</h4>
            <div class="form-group row">
                <label for="fname" class="col-sm-3 text-right control-label col-form-label">Nama Wisata</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="fname" placeholder="Nama Wisata" name="judul">
                </div>
            </div>
            <div class="form-group row">
                <label for="fname" class="col-sm-3 text-right control-label col-form-label">Kategori</label>
                <div class="col-sm-9">
                    <select type="text" class="form-control" id="fname" name="id_kategori">
                        <option disabled selected>Pilih Kategori</option>
                        @foreach ($kategoris as $kategori)
                            <option value="{{$kategori->id}}">{{$kategori->nama_kat}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="lname" class="col-sm-3 text-right control-label col-form-label">Alamat</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="lname" placeholder="Nama Jalan" name="jalan">
                </div>
            </div>
            <div class="form-group row">
                <label for="lname" class="col-sm-3 text-right control-label col-form-label"></label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="lname" placeholder="Kelurahan/Kecamatan" name="kelkec">
                </div>
            </div>
            <div class="form-group row">
                <label for="email1" class="col-sm-3 text-right control-label col-form-label"></label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="email1" placeholder="Kota/Kabupaten" name="kotakab">
                </div>
            </div>
            <div class="form-group row">
                <label for="cono1" class="col-sm-3 text-right control-label col-form-label"></label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="cono1" placeholder="Provinsi" name="provinsi" value="Sumatera Barat" readonly>
                </div>
            </div>
            <div class="form-group row">
                <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Isi informasi</label>
                <div class="col-sm-9">
                    <textarea class="form-control" name="konten"></textarea>
                </div>
            </div>
            <div class="form-group row">
                <label for="lname" class="col-sm-3 text-right control-label col-form-label">Peta</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="lname" placeholder="Masukkan Link" name="peta">
                </div>
            </div>
            <div class="form-group row">
                <label for="lname" class="col-sm-3 text-right control-label col-form-label">Foto 1</label>
                <div class="col-sm-9">
                    <input type="file" name="foto1">
                </div>
            </div>
            <div class="form-group row">
                <label for="lname" class="col-sm-3 text-right control-label col-form-label">Foto 2</label>
                <div class="col-sm-9">
                    <input type="file" name="foto2">
                </div>
            </div>
            <div class="form-group row">
                <label for="lname" class="col-sm-3 text-right control-label col-form-label">Foto 3</label>
                <div class="col-sm-9">
                    <input type="file" name="foto3">
                </div>
            </div>
        </div>
        <div class="border-top">
            <div class="card-body">
                <button type="submit" class="btn btn-primary">Input</button>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/admin/informasi/edit.blade.php
@extends('admin.master')

@section('content')



<div class="card">

<form action="{{url('informasi/'.$informasi->id)}}" method="post" enctype="multipart/form-data" class="form-horizontal">

    

@csrf

<input type="hidden" value='PUT' name='_method'>

        <div class="card-body">

            <h4 class="card-title">Ubah Informasi Wisata</h4>

            <div class="form-group row">

                <label for="fname" class="col-sm-3 text-right control-label col-form-label">Nama Wisata</label>

                <div class="col-sm-9">

                    <input type="text" value="{{ $informasi->judul }}" class="form-control" id="fname" placeholder="Nama Wisata" name="judul">

                </div>

            </div>

            <div class="form-group row">

                <label for="fname" class="col-sm-3 text-right control-label col-form-label">Kategori</label>

                <div class="col-sm-9">

                    <select type="text" class="form-control" id="fname" name="id_kategori">

                        <option disabled selected>Pilih Kategori</option>

                        @foreach ($kategoris as $kategori)

                            <option @if($kategori->id == $informasi->id_kategori) selected @endif value="{{$kategori->id}}">{{$kategori->nama_kat}}</option>

                        @endforeach

                    </select>

                </div>

            </div>

            <div class="form-group row">

                <label for="lname" class="col-sm-3 text-right control-label col-form-label">Alamat</label>

                <div class="col-sm-9">

                    <input type="text" value="{{ $informasi->jalan }}" class="form-control" id="lname" placeholder="Nama Jalan" name="jalan">

                </div>

            </div>

            <div class="form-group row">

                <label for="lname" class="col-sm-3 text-right control-label col-form-label"></label>

                <div class="col-sm-9">

                    <input type="text" value="{{ $informasi->kelkec }}" class="form-control" id="lname" placeholder="Kelurahan/Kecamatan" name="kelkec">

                </div>

            </div>

            <div class="form-group row">

                <label for="email1" class="col-sm-3 text-right control-label col-form-label"></label>

                <div class="col-sm-9">

                    <input type="text" class="form-control" value="{{ $informasi->kotakab }}" id="email1" placeholder="Kota/Kabupaten" name="kotakab">

                </div>

            </div>

            <div class="form-group row">

                <label for="cono1" class="col-sm-3 text-right control-label col-form-label"></label>

                <div class="col-sm-9">

                    <input type="text" class="form-control" id="cono1" placeholder="Provinsi" value="{{ $informasi->provinsi }}" name="provinsi" value="Sumatera Barat" readonly>

                </div>

            </div>

            <div class="form-group row">

                <label for="lname" class="col-sm-3 text-right control-label col-form-label">Status</label>

                <div class="col-sm-9">

                    <input type="radio" name="populer" value="Populer">Populer  
                    <br>
                    <input type="radio" name="populer" value="Rare">Jarang dikunjungi

                </div>

            </div>

            <div class="form-group row">

                <label for="cono1" class="col-sm-3 text-right control-label col-form-label">Isi informasi</label>

                <div class="col-sm-9">

                    <textarea class="form-control" name="konten">{{ $informasi->konten }}</textarea>

                </div>

            </div>

            <div class="form-group row">

                <label for="lname" class="col-sm-3 text-right control-label col-form-label">Peta</label>

                <div class="col-sm-9">

                    <input type="text" class="form-control" id="lname" value="{{ $informasi->peta }}" placeholder="Masukkan Link" name="peta">

                </div>

            </div>

            <div class="form-group row">

                <label for="lname" class="col-sm-3 text-right control-label col-form-label">Foto 1</label>

                <div class="col-sm-9">

                    <input type="file" name="foto1">

                </div>

            </div>

            <div class="form-group row">

                <label for="lname" class="col-sm-3 text-right control-label col-form-label">Foto 2</label>

                <div class="col-sm-9">

                    <input type="file" name="foto2">

                </div>

            </div>

            <div class="form-group row">

                <label for="lname" class="col-sm-3 text-right control-label col-form-label">Foto 3</label>

                <div class="col-sm-9">

                    <input type="file" name="foto3">

                </div>

            </div>

        </div>

        <div class="border-top">

            <div class="card-body">

                <button type="submit" class="btn btn-primary">Ubah</button>

            </div>

        </div>

    </form>

</div>

@endsection

resources/views/admin/informasi/index.blade.php
@extends('admin.master')

@section('content')

<div class="card">

    <div class="card-body">

        <h5 class="card-title m-b-0">Daftar Informasi Wisata</h5>

    </div>

    <table class="table">

        <thead>

            <tr>

            <th scope="col" class="text-center"><strong>ID</strong></th>

            <th scope="col" class="text-left"><strong>Nama Wisata</strong></th>

            <th scope="col" class="text-center"><strong>Kategori</strong></th>

            <th scope="col" class="text-jalan"><strong>Jalan</strong></th>

            <th scope="col" class="text-left"><strong>Kelurahan/Kecamatan</strong></th>

            <th scope="col" class="text-left"><strong>Kota/Kabupaten</strong></th>

            <th scope="col" colspan="2" class="text-center"><strong>Aksi</strong></th>

            </tr>

        </thead>

        <tbody>

        @foreach($informasis as $informasi)

            @php

                $nama_kat = App\Kategori::where('id', $informasi->id_kategori)->first();

            @endphp

            <tr>

            <td scope="row" class="text-center">{{$informasi->id}}</td>

            <td class="text-left">{{$informasi->judul}}</td>

            <td class="text-center">{{$nama_kat->nama_kat}}</td>

            <td class="text-left">{{$informasi->jalan}}</td>

            <td class="text-left">{{$informasi->kelkec}}</td>

            <td class="text-left">{{$informasi->kotakab}}</td>

            <td class="text-center">

                <a href="{{ url('informasi/'. $informasi->id .'/edit') }}" class="btn btn-info btn-sm">Ubah</a>

            </td>

            <td>

                <form onsubmit = "return confirm('Apakah yakin informasi {{$informasi->judul}} dihapus?')" class="d-inline" action="{{route('informasi.destroy',['id' => $informasi->id])}}" method="post">

                    @csrf

                    <input type="hidden" name="_method" value="DELETE">

                    <button type="submit" class="btn btn-danger btn-sm">Hapus</button>

                </form>

            </td>

            </tr>

        @endforeach

        </tbody>

    </table>



    <nav>

        {{$informasis->links()}}

    </nav>

    

    <!-- <div class="modal fade" id="Modal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">

        <div class="modal-dialog" role="document">

            <div class="modal-content">

                <div class="modal-header">

                    <h5 class="modal-title" id="exampleModalLabel">Hapus Data Informasi</h5>

                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">

                        <span aria-hidden="true">&times;</span>

                    </button>

                </div>

                <div class="modal-body">

                        Apakah yakin informasi {{$informasi->judul}} dihapus?

                </div>

                <div class="modal-footer">

                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>

                    <form action="{{ url('informasi/'. $informasi->id ) }}" method="post">

                        @csrf

                        <input type="hidden" name="_method" value="DELETE">

                        <button type="submit" class="btn btn-danger">Yakin</button>

                    </form>

                </div>

            </div>

        </div>

    </div> -->

</div>

@endsection